version: "3.9"
services:
  database:
    image: postgres:15
    container_name: database
    env_file:
      - .env_example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  database_two:
    image: postgres:15
    container_name: database_two
    env_file:
      - .env_example
    ports:
      - "5433:5433"
    volumes:
      - postgres_data_two:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_two: